# Generated by Django 5.2.5 on 2025-09-13 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('addition', 'Stock Addition'), ('removal', 'Stock Removal'), ('correction', 'Quantity Correction'), ('damage', 'Damaged Goods'), ('return', 'Customer Return')], help_text='Type of adjustment being made', max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for additions, negative for removals')),
                ('previous_quantity', models.IntegerField(help_text='Quantity before adjustment')),
                ('new_quantity', models.IntegerField(help_text='Quantity after adjustment')),
                ('notes', models.TextField(blank=True, help_text='Reason for adjustment or additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, help_text='Optional reference number or ID for tracking', max_length=64, null=True)),
                ('adjusted_by', models.ForeignKey(help_text='User who made this adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The inventory item being adjusted', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='tracker.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item', 'created_at'], name='tracker_inv_item_id_71cf40_idx'), models.Index(fields=['adjustment_type'], name='tracker_inv_adjustm_b7d6e2_idx'), models.Index(fields=['reference'], name='tracker_inv_referen_c65f17_idx')],
            },
        ),
    ]
