# Generated by Django 4.2.24 on 2025-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_inventoryadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', help_text='User timezone for displaying dates and times', max_length=100),
        ),
    ]
